name: Update Lotto Data

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 13 * * 6' # 매주 토요일 밤 실행 (UTC 기준)
  workflow_dispatch: # 수동 실행 버튼

permissions:
  contents: write  # 기계가 저장소에 글을 쓸 수 있는 권한 부여

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 코드 가져오기
      uses: actions/checkout@v3

    - name: 파이썬 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 필요한 도구 설치
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: 로또 정보 긁어오기 (실행)
      run: python update.py

    - name: 결과 깃허브에 올리기 (Commit & Push)
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # results 폴더의 변경사항을 강제로 다 담습니다
        git add results/
        
        # 변경사항이 있을 때만 커밋하고 푸시합니다 (에러 방지)
        git commit -m "Add new lotto data (Auto)" || echo "변경사항이 없어 커밋하지 않습니다."
        git push
